### PR TITLE
Update electrum/gui/qt/main_window.py

### PR DESCRIPTION
**Pull request by kentlangley**
Updated several text msg entries for grammar and clarity. I also swapped out the seed icon.

### CODE REVIEW

**Review by turcol — APPROVED** [review]
The use of CivX and CIVX is not interchangeable. We should use CIVX when referring to the ticker

**Review by turcol — CHANGES_REQUESTED** [review]
Please remove the .DS_Store file that was uploaded with the seed.png file .. You can add to your local .gitignore a line with .DS_Store to avoid uploading this kind o files

**Comment by kentlangley** [comment]
added .gitignore and removed that file. thanks.

**Comment by turcol** [comment]
Thanks for the updates !

**Pull request merged**
